# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/database/schema.rs"

# import_types = ["diesel::sql_types::*", "crate::database::DbIndiFuncMapping"]
# filter = { except_tables = ["set_indicators", "indicator_default_func"  # custom indifunc enum
# ]}
patch_file = "diesel_schema.patch"
