version: '3.5'

services:
    postgres:
        # container_name: backtest-postgres
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
            PGDATA: /data/postgres
        volumes:
            - ${POSTGRES_DATA_VOLUME:-postgres_backtest}:/data/postgres
        ports:
            - 5432:5432
        # networks:
        #     - postgres_backtest
        restart: unless-stopped

    pgadmin:
        # container_name: backtest-pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - ${PGADMIN_PORT:-5050}:80
        # networks:
        #     - postgres_backtest
        restart: unless-stopped

    phppgadmin:
      # container_name: backtest-phppgadmin
      image: dockage/phppgadmin
      # networks:
      #     - postgres_backtest
      ports:
          - ${PHPPGADMIN_PORT:-8080}:80
          - ${PHPPGADMIN_SECURE_PORT:-8443}:443
      environment:
          PHP_PG_ADMIN_SERVER_DESC: Backtest
          PHP_PG_ADMIN_SERVER_HOST: postgres
          PHP_PG_ADMIN_SERVER_PORT: 5432
          PHP_PG_ADMIN_SERVER_SSL_MODE: allow
          PHP_PG_ADMIN_SERVER_DEFAULT_DB:  ${POSTGRES_DATABASE:-test}
          PHP_PG_ADMIN_SERVER_PG_DUMP_PATH: /usr/bin/pg_dump
          PHP_PG_ADMIN_SERVER_PG_DUMPALL_PATH: /usr/bin/pg_dumpall

          PHP_PG_ADMIN_DEFAULT_LANG: auto
          PHP_PG_ADMIN_AUTO_COMPLETE: "default on"
          PHP_PG_ADMIN_EXTRA_LOGIN_SECURITY: 0
          PHP_PG_ADMIN_OWNED_ONLY: 0
          PHP_PG_ADMIN_SHOW_COMMENTS: 1
          PHP_PG_ADMIN_SHOW_ADVANCED: 0
          PHP_PG_ADMIN_SHOW_SYSTEM: 0
          PHP_PG_ADMIN_MIN_PASSWORD_LENGTH: 1
          PHP_PG_ADMIN_LEFT_WIDTH: 200
          PHP_PG_ADMIN_THEME: default
          PHP_PG_ADMIN_SHOW_OIDS: 0
          PHP_PG_ADMIN_MAX_ROWS: 30
          PHP_PG_ADMIN_MAX_CHARS: 50
          PHP_PG_ADMIN_USE_XHTML_STRICT: 0
          PHP_PG_ADMIN_HELP_BASE: http://www.postgresql.org/docs/%s/interactive/
          PHP_PG_ADMIN_AJAX_REFRESH: 3
      restart: unless-stopped

volumes:
  pgadmin:
  # postgres_backtest:
