---
name: ALF2
name_indi: Adaptive_Laguerre_filter_2
indi_type: SingleLineColorChange
inputs:
# input ENUM_TIMEFRAMES TimeFrame       = PERIOD_CURRENT; // Time frame
  - - Int
    - - 0.0  # current
      # - 1.0  # M1
      - 5.0  # M5
      - 19.0 # D1
      # - 21.0 # MN1
      - 2.0    # 5m 10m 15m 30m 2h 4h 8h 1D
# input double          LaggPeriod      = 10;             // Laguerre period
  - - Double
    - - 10.0
      - 4.0
      - 24.0
      - 2.0
# input double          LaggSmooth      = 0.5;            // Laguerre "smooth"
  - - Double
    - - 0.5
      - 0.1
      - 1.5
      - 0.2
# input enPrices        Price           = pr_median;      // Price
  - - Int
    - - 0.0
      - 0.0
      - 21.0
      - 1.0
# input bool            AlertsOn        = false;          // Turn alerts on?
# input bool            AlertsOnCurrent = true;           // Alert on current bar?
# input bool            AlertsMessage   = true;           // Display messageas on alerts?
# input bool            AlertsSound     = false;          // Play sound on alerts?
# input bool            AlertsEmail     = false;          // Send email on alerts?
# input bool            AlertsNotify    = false;          // Send push notification on alerts?
# input bool            Interpolate     = true;           // Interpolate mtf data ?
buffers:
# SetIndexBuffer(0,lagg1 ,INDICATOR_DATA);
# SetIndexBuffer(1,lagg1c,INDICATOR_COLOR_INDEX);
# SetIndexBuffer(2,count ,INDICATOR_CALCULATIONS);
  - 1
colors:
  - 0
  - 1
  - 2
shift: 0

