---
name: Aroon_Osci_Zero
name_indi: Aroon_oscillator_1.7
indi_type: ZeroLineCross
inputs:
# input ENUM_TIMEFRAMES TimeFrame       = PERIOD_CURRENT; // Time frame
  - - Int
    - - 0.0  # current
      # - 1.0  # M1
      - 5.0  # M5
      - 19.0 # D1
      # - 21.0 # MN1
      - 2.0    # 5m 10m 15m 30m 2h 4h 8h 1D
# input int             AroonPeriod     = 25;             // Aroon oscillator period
  - - Int
    - - 25.0
      - 13.0
      - 35.0
      - 2.0
# input enPrices        PriceHigh       = pr_high;        // Price to use for high
  - - Int
    - - 0.0
      - 0.0
      - 21.0
      - 1.0
# input enPrices        PriceLow        = pr_low;         // Price to use for low
  - - Int
    - - 0.0
      - 0.0
      - 21.0
      - 1.0
# input int             LevelsPeriod    = 0;              // Levels period (0 to use the same as Arron period)
  - - Int
    - - 0.0
      - 10.0
      - 35.0
      - 3.0
# input double          LevelsUp        = 80;             // Levels up
  - - Int
    - - 80.0
      - 70.0
      - 90.0
      - 5.0
# input double          LevelsDown      = 20;             // Levels down
  - - Int
    - - 20.0
      - 10.0
      - 30.0
      - 5.0
# input double          FilterValue     = 0;              // Filter (<=0, for no filter)
  - - Double
    - - 0.0
      - 0.0
      - 1.0
      - 0.1
# input int             FilterPeriod    = 0;              // Filter period (<=0 for using Aroon period)
  - - Int
    - - 0.0
      - 10.0
      - 35.0
      - 3.0
# input enFilterWhat    FilterWhat      = _fltVal;        // Filter what?
  - - Int
    - - 0.0
      - 0.0
      - 2.0
      - 1.0
# input bool            alertsOn        = false;          // Turn alerts on?
# input bool            alertsOnCurrent = true;           // Alert on current bar?
# input bool            alertsMessage   = true;           // Display messageas on alerts?
# input bool            alertsSound     = false;          // Play sound on alerts?
# input bool            alertsEmail     = false;          // Send email on alerts?
# input bool            alertsNotify    = false;          // Send push notification on alerts?
# input bool            Interpolate     = true;           // Interpolate mtf data ?
buffers:
   # SetIndexBuffer(0,oscu,INDICATOR_DATA);
   # SetIndexBuffer(1,oscd,INDICATOR_DATA);
   # SetIndexBuffer(2,levu,INDICATOR_DATA);
   # SetIndexBuffer(3,levd,INDICATOR_DATA);
   # SetIndexBuffer(4,osc  ,INDICATOR_DATA);
   # SetIndexBuffer(5,oscc ,INDICATOR_COLOR_INDEX);
   # SetIndexBuffer(6,prh  ,INDICATOR_CALCULATIONS);
   # SetIndexBuffer(7,prl  ,INDICATOR_CALCULATIONS);
   # SetIndexBuffer(8,count,INDICATOR_CALCULATIONS);
  - 4
shift: 0

