---
name: Ash
name_indi: ASH
# without ex5
indi_type: ZeroLineCross
# //--- plot ASH
# #property indicator_label1  "ASH"
# #property indicator_type1   DRAW_COLOR_HISTOGRAM
# #property indicator_color1  clrBlue,clrRed,clrDarkGray
# #property indicator_style1  STYLE_SOLID
# #property indicator_width1  2
inputs:
# input uint                 InpPeriod         =  9;             // Period
  - - Int
    - - 9.0
      - 4.0
      - 20.0
      - 1.0
# input uint                 InpPeriodSm       =  2;             // Smoothing
  - - Int
    - - 2.0
      - 0.0
      - 10.0
      - 1.0
# input ENUM_MODE            InpMode           =  MODE_RSI;      // Mode
#    MODE_RSI,   // RSI
#    MODE_STO    // Stochastic
  - - Int
    - - 0.0
      - 0.0
      - 1.0
      - 1.0
# input ENUM_MA_METHOD       InpMethod         =  MODE_SMA;      // Method
# MODE_SMA 0 Simple averaging
# MODE_EMA 1 Exponential averaging
# MODE_SMMA 2 Smoothed averaging
# MODE_LWMA 3 Linear-weighted averaging
  - - Int
    - - 0.0
      - 0.0
      - 3.0
      - 1.0
# input ENUM_APPLIED_PRICE   InpAppliedPrice   =  PRICE_CLOSE;   // Applied price
# PRICE_CLOSE 0 Close price
# PRICE_OPEN 1 Open price
# PRICE_HIGH 2 The maximum price for the period
# PRICE_LOW 3 The minimum price for the period
# PRICE_MEDIAN 4 Median price, (high + low)/2
# PRICE_TYPICAL 5 Typical price, (high + low + close)/3
# PRICE_WEIGHTED 6 Weighted close price, (high + low + close + close)/4
  - - Int
    - - 0.0
      - 0.0
      - 6.0
      - 1.0
buffers:
  - 0
shift: 0

