---
name: COG
name_indi: center-of-gravity-extended-indicator
indi_type: ColorChange
inputs:
# Period
  - - Int
    - - 32.0
      - 20.0
      - 45.0
      - 2.0
# Price
  - - Int
    - - 4.0
      - 0.0
      - 6.0
      - 1.0
# color change
  - - Int
    - - 0.0
      - 0.0
      - 3.0
      - 1.0
buffers:
  - 1
colors:
  - 0
  - 1
  - 2
shift: 0

