---
name: Velocity_norm
name_indi: Velocity_-_normalized
indi_type: SingleLineColorChange
inputs:
# input ENUM_TIMEFRAMES TimeFrame       = PERIOD_CURRENT; // Time frame
  - - Int
    - - 0.0  # current
      # - 1.0  # M1
      - 5.0  # M5
      - 19.0 # D1
      # - 21.0 # MN1
      - 2.0    # 5m 10m 15m 30m 2h 4h 8h 1D
# input int             VelPeriod       = 32;             // Velocity period
  - - Int
    - - 32.0
      - 20.0
      - 45.0
      - 2.0
# input enPrices        VelPrice        = pr_close;       // Price to use
  - - Int
    - - 0.0
      - 0.0
      - 21.0
      - 1.0
# input enNormMethod    NormMethod      = nm_atr;         // Normalization method
  - - Int
    - - 0.0
      - 0.0
      - 3.0
      - 1.0
# input enColorOn       ColorOn         = cc_onLevels;    // Color change :
  - - Int
    - - 0.0
      - 0.0
      - 2.0
      - 1.0
# input int             MinMaxPeriod    = 50;             // Floating levels period (<= 1 to use velocity period)
  - - Int
    - - 32.0
      - 20.0
      - 45.0
      - 2.0
# input double          LevelUp         = 80.0;           // Up level %
  - - Int
    - - 80.0
      - 70.0
      - 95.0
      - 5.0
# input double          LevelDown       = 20.0;           // Down level %
  - - Int
    - - 20.0
      - 5.0
      - 30.0
      - 5.0
# input bool            alertsOn        = false;          // Turn alerts on?
# input bool            alertsOnCurrent = true;           // Alert on current bar?
# input bool            alertsMessage   = true;           // Display messageas on alerts?
# input bool            alertsSound     = false;          // Play sound on alerts?
# input bool            alertsEmail     = false;          // Send email on alerts?
# input bool            alertsNotify    = false;          // Send push notification on alerts?
# input bool            Interpolate     = true;           // Interpolate mtf data ?

buffers:
  - 6
colors:
    - 0  # neutral
    - 1  # up
    - 2  # down
shift: 0

