---
params_file: expert_params.set
# use wine on Linux
wine: true
# path to terminal64.exe to execute :: use C:/ for wine as well
terminal_exe: "C:/Program Files/MetaTrader 5/terminal64.exe"
# full path workdir to cwd into
workdir: "/home/stefan/.wine/drive_c/Program Files/MetaTrader 5"
# workdir: "C:/Users/stele/AppData/Roaming/MetaQuotes/Terminal/D0E8209F77C8CF37AD8BF550E51FF075"
# workdir: "C:\\Users\\stele\\AppData\\Roaming\\MetaQuotes\\Terminal\\D0E8209F77C8CF37AD8BF550E51FF075"
reports: reports
# expert with Windows-style "\"
expert: "backtestd\\backtestd-expert.ex5"
period: D1
login: "19768"
use_remote: true
use_local: true
replace_report: true
shutdown_terminal: true
deposit: 100000
currency: USD
leverage: 500
execution_mode: 0

# jj2piqfv
