---
name: bt_run
date:
  - 2018-01-01T00:00:00-00:00
  - 2019-12-11T00:00:00-00:00
backtest_model: 2
    # EveryTick = 0,     // "Every tick"
    # OneMinuteOHLC = 1, // "1 minute OHLC"
    # OpenPrice = 2,     // "Open price only"
    # MathCalc = 3,      // "Math calculations"
    # EveryTickReal = 4, // "Every tick based on real ticks"
optimize: 2
    # Disabled = 0,   // optimization disabled
    # Complete = 1,   // "Slow complete algorithm"
    # Genetic = 2,    // "Fast genetic based algorithm"
    # AllSymbols = 3, // "All symbols selected in Market Watch"
optimize_crit: 6
    # Balance = 0,         // the maximum balance value,
    # BalanceProf = 1,     // the maximum value of product of the balance and profitability,
    # BalancePayoff = 2,   // the product of the balance and expected payoff,
    # Drawdown = 3,        // the maximum value of the expression (100% - Drawdown)*Balance,
    # BalanceRecovery = 4, // the product of the balance and the recovery factor,
    # BalanceSharpe = 5,   // the product of the balance and the Sharpe Ratio,
    # Custom = 6, // a custom optimization criterion received from the OnTester() function in the Expert Advisor).
visual: true
symbols:
  - EURUSD
indi_set:
  confirm2: ~
  confirm3: ~
  exit: ~
  cont: ~
  baseline: ~
  volume: ~
  # confirm: config/indicator/baseline/ALF2_baseline.yaml
