---
name: AO
inputs:
  - - 5.0
    - 19.0
    - 2.0
  - - 0.0
    - 3.0
    - 1.0
  - - 3.0
    - 15.0
    - 2.0
  - - 0.0
    - 21.0
    - 1.0
  - - 0.0
    - 3.0
    - 1.0
  - - 22.0
    - 44.0
    - 2.0
  - - 0.0
    - 21.0
    - 1.0
shift: 0