---
name: Aroon_Osci_Zero
inputs:
  - - 5.0
    - 19.0
    - 2.0
  - - 13.0
    - 35.0
    - 2.0
  - - 0.0
    - 21.0
    - 1.0
  - - 0.0
    - 21.0
    - 1.0
  - - 10.0
    - 35.0
    - 3.0
  - - 70.0
    - 90.0
    - 5.0
  - - 10.0
    - 30.0
    - 5.0
  - - 0.0
    - 1.0
    - 0.10000000149011612
  - - 10.0
    - 35.0
    - 3.0
  - - 0.0
    - 2.0
    - 1.0
shift: 0