---
name: Corr_momentum_orig_val
inputs:
  - - 20.0
    - 45.0
    - 2.0
  - - -5.0
    - 40.0
    - 5.0
  - - 0.0
    - 21.0
    - 1.0
  - - 0.0
  - - 15.0
    - 40.0
    - 2.0
  - - 70.0
    - 95.0
    - 5.0
  - - 5.0
    - 30.0
    - 5.0
shift: 0