---
name: Corr_avg
inputs:
  - - 5.0
    - 19.0
    - 2.0
  - - 0.0
    - 3.0
    - 1.0
  - - 6.0
    - 24.0
    - 2.0
  - - 0.0
    - 21.0
    - 1.0
  - - 0.0
    - 1.0
    - 0.10000000149011612
  - - 0.0
    - 3.0
    - 1.0
  - - 15.0
    - 35.0
    - 2.0
  - - 75.0
    - 95.0
    - 5.0
  - - 5.0
    - 25.0
    - 5.0
shift: 0