---
name: EO
inputs:
  - - 5.0
    - 19.0
    - 2.0
  - - 3.0
    - 20.0
    - 2.0
  - - 22.0
    - 46.0
    - 2.0
  - - 0.0
    - 3.0
    - 1.0
  - - 0.0
    - 21.0
    - 1.0
  - - 0.0
    - 2.0
    - 1.0
shift: 0