---
name: QWMA
filename: QWMA_ca
class: ColorChange
inputs:

# input ENUM_TIMEFRAMES TimeFrame        = PERIOD_CURRENT; // Time frame
    - - 0.0  # current
      # - 1.0  # M1
      - 5.0  # M5
      - 19.0 # D1
      # - 21.0 # MN1
      - 2.0    # 5m 10m 15m 30m 2h 4h 8h 1D
# input int             MaPeriod         = 25;             // MA period
    - - 25.0
      - 15.0
      - 35.0
      - 2.0
# input double          MaSpeed          =  2;             // MA "speed"
    - - 2.0
      - 0.0
      - 10.0
      - 0.5
# input enPrices        MaPrice          = pr_close;       // Average price
    - - 0.0
      - 0.0
      - 21.0
      - 1.0
# input int             CorrectionPeriod =  0;             // Deviations period (<1 same as ma period, -1 no correction)
    - - 0.0
      - -1.0
      - 1.0
      - 1.0
# input chgColor        ColorOn          = chg_onLevel;    // Color change on :
   # chg_onSlope,  // change color on slope change
   # chg_onLevel,  // Change color on outer levels cross
   # chg_onMiddle, // Change color on middle level cross
   # chg_onQwma    // Change color on QWMA original cross
    - - 0.0
      - 0.0
      - 3.0
      - 1.0
# input int             FlPeriod         = 25;             // Period for finding floating levels
    - - 25.0
      - 15.0
      - 35.0
      - 2.0
# input double          FlUp             = 90;             // Upper level %
    - - 90.0
      - 75.0
      - 95.0
      - 5.0
# input double          FlDown           = 10;             // Lower level %
    - - 10.0
      - 5.0
      - 25.0
      - 5.0
# input bool            AlertsOn         = false;          // Turn alerts on?
# input bool            AlertsOnCurrent  = true;           // Alert on current bar?
# input bool            AlertsMessage    = true;           // Display messageas on alerts?
# input bool            AlertsSound      = false;          // Play sound on alerts?
# input bool            AlertsEmail      = false;          // Send email on alerts?
# input bool            AlertsNotify     = false;          // Send push notification on alerts?
# input bool            Interpolate      = true;           // Interpolate when in multi time frame mode?

buffers:
   # SetIndexBuffer(0,fup  ,INDICATOR_DATA);
   # SetIndexBuffer(1,fdn  ,INDICATOR_DATA);
   # SetIndexBuffer(2,mid  ,INDICATOR_DATA);
   # SetIndexBuffer(3,work ,INDICATOR_DATA);
   # SetIndexBuffer(4,qwma ,INDICATOR_DATA);
   # SetIndexBuffer(5,qwmac,INDICATOR_COLOR_INDEX);
   # SetIndexBuffer(6,count,INDICATOR_CALCULATIONS);
  - 5 # COLOR_INDEX
params:
  - 0  # neutral
  - 1  # up
  - 2  # down
shift: 0
