---
name: Velocity_norm
inputs:
  - - 5.0
    - 19.0
    - 2.0
  - - 20.0
    - 45.0
    - 2.0
  - - 0.0
    - 21.0
    - 1.0
  - - 0.0
    - 3.0
    - 1.0
  - - 0.0
    - 2.0
    - 1.0
  - - 20.0
    - 45.0
    - 2.0
  - - 70.0
    - 95.0
    - 5.0
  - - 5.0
    - 30.0
    - 5.0
shift: 0