---
name: Plombiers
name_indi: plombiers-indicator
indi_type: PriceCrossInverted
inputs:
# input int  bars_IN = 145;   // data length
  - - Int
    - - 145.0
      - 35.0
      - 200.0
      - 20.0
# input intType SP = i2 (2);      // curve's order
# enum
  - - Int
    - - 2.0
      - 0.0
      - 4.0
      - 1.0
# input int N_Shift1 = 0;     // shift back into the history
  - - Int
    - - 0.0
# input int Forecast=0;       // length of channel into the "future"
  - - Int
    - - 0.0
# input double kstd = 2.1415; // standart deviation factor
  - - Int
    - - 2.1415
      - 1.1415
      - 3.2
      - 0.2
# input bool Oscilator=true;  // Is oscillator on the display?
  - - Int
    - - 1.0
# input int N_Buff=1;         // displayed oscillator's buffer
  - - Int
    - - 1.0
# input int Ka=21;            // Line calculation period %K.
  - - Int
    - - 21.0
      - 14.0
      - 27.0
      - 2.0
# input int La=7;             // Averaging period %D
  - - Int
    - - 7.0
      - 3.0
      - 12.0
      - 2.0
# input int Za=1;             // Deceleration
  - - Int
    - - 9.0
      - 5.0
      - 15.0
      - 1.0
# input ENUM_MA_METHOD Oe=MODE_SMA; // Averaging method
  - - Int
    - - 0.0
      - 0.0
      - 3.0
      - 1.0
# input ENUM_STO_PRICE Me=STO_CLOSECLOSE;  // Stochastic's price value
  - - Int
    - - 0.0
      - 0.0
      - 1.0
      - 1.0
# input int DIGf = -99; // Number of decimal points.-99 Digits
  - - Int
    - - -99.0
      - -199.0
      - 0.0
      - 50.0

buffers:
# buffer
  - 5
shift: 0

