---
name: YMA
name_indi: YGMA
# use YMA and GMA from the same indi
indi_type: OnChart
inputs:
    # YMA
  - - Int
    - - 21.0
      - 9.0
      - 35.0
      - 2.0
# GMA
  - - Int
    - - -1.0
buffers:
  - 0
shift: 0

